apiVersion: apps/v1
kind: Deployment
metadata:
  name: healer-app
  namespace: healer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healer-app
  template:
    metadata:
      labels:
        app: healer-app
    spec:
      containers:
        - name: healer-app
          image: shashankramakanth/healer-app:v1.0.0
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
