apiVersion: v1
kind: Service
metadata:
  name: healer-app
  namespace: healer
  labels:
    app: healer-app
spec:
  selector:
    app: healer-app
  ports:
    - name: http-metrics
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
